a=float(input("nhap gia tri thu nhat la :"))
b=float(input("nhap gia tri thu hai la :"))
c=float(input("nhap gia tri thu ba la :"))
S1=a*a-2*b+(a*b)/(c*c+3)
S2=(b*b-4*a*c)/(2*a)

S3=3*a-b**3+2*(c*c+1)**(1/2)
S4=(a*a/b-4*(a/(b*c))+1)**(1/2)
x1=round(S1,3)
x2=round(S2,3)
x3=round(S3,3)
x4=round(S4,3)
print("ket qua cua bieu thuc mot la : ",x1)
print("ket qua cua bieu thuc hai la : ",x2)
print("ket qua cua bieu thuc ba la : ",x3)
print("ket qua cua bieu thuc bon la : ",x4)