a=float(input("nhap gia tri thu nhat la :"))
b=float(input("nhap gia tri thu hai la :"))
c=float(input("nhap gia tri thu ba la :"))
S1=a*a-2*b+(a*b)/(c*c+3)
S2=(b*b-4*a*c)/(2*a)
import math
S3=3*a-b**3+2*math.sqrt(c*c+1)
S4=math.sqrt(a*a/b-4*(a/(b*c))+1)
print("")
print("S1=a^2-2.b+(a.b)/(c^2+3)")
print("S2=(b^2-4.a.c)/(2.a)")
print("S3=3.a-b^3+2.(c^2+1)^(1/2)")
print("S4=(a^2/b-4.(a/(b.c))+1)^(1/2)")
print("	")
print("ket qua cua bieu thuc mot la : ",S1)
print("ket qua cua bieu thuc hai la : ",S2)
print("ket qua cua bieu thuc ba la : ",S3)
print("ket qua cua bieu thuc bon la : ",S4)